name: Robot Framework Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
          pip install robotframework-databaselibrary
          pip install webdriver-manager

      - name: Install Chrome for Testing
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.182/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

      - name: Install ChromeDriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.182/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Verify installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Robot Tests
        run: |
          robot --outputdir results tests api_tests db_tests